-- MySQL Script generated by MySQL Workbench
-- Thu Jul 14 09:46:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dreamdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dreamdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dreamdb` DEFAULT CHARACTER SET utf8 ;
USE `dreamdb` ;

-- -----------------------------------------------------
-- Table `dreamdb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamdb`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL COMMENT '0: Inactivo, 1: Activo',
  `role` INT NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `location` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `photo` TEXT NULL,
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamdb`.`ownership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamdb`.`ownership` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Propiedades',
  `name` VARCHAR(128) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `photo` TEXT(1000) NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `owner_id_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `owner_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `dreamdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamdb`.`advertising`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamdb`.`advertising` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `photo` TEXT NOT NULL,
  `create_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamdb`.`interest_advertising`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamdb`.`interest_advertising` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_by` INT NULL,
  `account_id` INT NOT NULL,
  `advertising_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `advertising_id_idx` (`advertising_id` ASC) VISIBLE,
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `advertising_id`
    FOREIGN KEY (`advertising_id`)
    REFERENCES `dreamdb`.`advertising` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `dreamdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dreamdb`.`pickup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dreamdb`.`pickup` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `arrival_at` DATETIME NOT NULL,
  `status` INT NOT NULL COMMENT '-1, rechazado\n0, sin aceptar\n1, aceptado',
  PRIMARY KEY (`id`),
  INDEX `account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `dreamdb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
